// Packs the binary 3D assets into dist/characters.js as base64 strings, so
// the game can use them even when index.html is opened straight from disk
// (browsers do not let file:// pages fetch files, but they do run scripts).
import fs from 'node:fs';
import path from 'node:path';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const dir = path.join(root, 'assets', 'characters');
const out = path.join(root, 'dist', 'characters.js');

const entries = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.glb')).sort() : [];
const lines = entries.map((f) => {
  const b64 = fs.readFileSync(path.join(dir, f)).toString('base64');
  return `  ${JSON.stringify(path.basename(f, '.glb'))}: ${JSON.stringify(b64)},`;
});
const body = `// Generated by tools/pack-assets.mjs from assets/characters/*.glb - do not edit.\nwindow.__CHARACTER_ASSETS = {\n${lines.join('\n')}\n};\n`;
fs.mkdirSync(path.dirname(out), { recursive: true });
if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== body) fs.writeFileSync(out, body);
console.log(`packed ${entries.length} character asset(s) into dist/characters.js (${(body.length / 1e6).toFixed(2)} MB)`);
