// Packs the binary 3D assets into dist/characters.js as base64 strings, so
// the game can use them even when index.html is opened straight from disk
// (browsers do not let file:// pages fetch files, but they do run scripts).
// Models: assets/characters/*.glb; texture layers: assets/characters/textures
// (listed in layers.json, and the horse's in horse.json). Trees:
// assets/trees/trees.glb and its textures (listed in textures/trees.json).
import fs from 'node:fs';
import path from 'node:path';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const dir = path.join(root, 'assets', 'characters');
const out = path.join(root, 'dist', 'characters.js');
const b64 = (file) => fs.readFileSync(file).toString('base64');

const entries = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.glb')).sort() : [];
const lines = entries.map((f) => `  ${JSON.stringify(path.basename(f, '.glb'))}: ${JSON.stringify(b64(path.join(dir, f)))},`);

const texDir = path.join(dir, 'textures');
const manifest = path.join(texDir, 'layers.json');
let textures = 0;
if (fs.existsSync(manifest)) {
  const { size, layers } = JSON.parse(fs.readFileSync(manifest, 'utf8'));
  const packed = {};
  for (const [name, files] of Object.entries(layers)) {
    packed[name] = files.map((f) => (f ? b64(path.join(texDir, f)) : null));
    textures += files.filter(Boolean).length;
  }
  const tex = { size, layers: packed };
  const { tiles } = JSON.parse(fs.readFileSync(manifest, 'utf8'));
  if (tiles) {
    const tl = {};
    for (const [name, files] of Object.entries(tiles.layers)) {
      tl[name] = files.map((f) => b64(path.join(texDir, f)));
      textures += files.length;
    }
    tex.tiles = { size: tiles.size, layers: tl, repeat: tiles.repeat };
  }
  lines.push(`  textures: ${JSON.stringify(tex)},`);
}
// the horse's own layers (horse.json): colour layers and normal maps
const horseManifest = path.join(texDir, 'horse.json');
if (fs.existsSync(horseManifest)) {
  const { size, layers, normals = {} } = JSON.parse(fs.readFileSync(horseManifest, 'utf8'));
  const packed = { size, layers: {}, normals: {} };
  for (const [name, files] of Object.entries(layers)) {
    packed.layers[name] = files.map((f) => (f ? b64(path.join(texDir, f)) : null));
    textures += files.filter(Boolean).length;
  }
  for (const [name, file] of Object.entries(normals)) {
    packed.normals[name] = b64(path.join(texDir, file));
    textures++;
  }
  lines.push(`  horseTextures: ${JSON.stringify(packed)},`);
}

// the trees (tools/trees/build_trees.py): one model file, an atlas and a bark
// texture per kind
const treeDir = path.join(root, 'assets', 'trees');
const treeManifest = path.join(treeDir, 'textures', 'trees.json');
let trees = 0;
if (fs.existsSync(path.join(treeDir, 'trees.glb')) && fs.existsSync(treeManifest)) {
  const { atlasSize, barkSize, kinds } = JSON.parse(fs.readFileSync(treeManifest, 'utf8'));
  const packed = { atlasSize, barkSize, kinds: {} };
  const tex = (f) => b64(path.join(treeDir, 'textures', f));
  for (const [kind, k] of Object.entries(kinds)) {
    packed.kinds[kind] = { atlas: k.atlas.map(tex), bark: k.bark.map(tex), variants: k.variants };
    textures += k.atlas.length + k.bark.length;
  }
  lines.push(`  trees: ${JSON.stringify(b64(path.join(treeDir, 'trees.glb')))},`);
  lines.push(`  treeTextures: ${JSON.stringify(packed)},`);
  trees = 1;
}

const body = `// Generated by tools/pack-assets.mjs from assets/characters and assets/trees - do not edit.\nwindow.__CHARACTER_ASSETS = {\n${lines.join('\n')}\n};\n`;
fs.mkdirSync(path.dirname(out), { recursive: true });
if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== body) fs.writeFileSync(out, body);
console.log(`packed ${entries.length + trees} model(s) and ${textures} texture(s) into dist/characters.js (${(body.length / 1e6).toFixed(2)} MB)`);
